<?php
/**
 * ConfReport english translation
 * @package YetiForce.Language
 * @copyright YetiForce Sp. z o.o.
 * @license YetiForce Public License 3.0 (licenses/LicenseEN.txt or yetiforce.com)
 */
$languageStrings = [
	'ConfReport' => '服务器参数设置',
	'LBL_CONFIGURATION' => '服务器参数设置',
	'LBL_CONFREPORT_DESCRIPTION' => '允许您验证主服务器设置与推荐参数的兼容性。',
	'LBL_PARAMETER' => '参数',
	'LBL_VALUE' => '当前配置',
	'LBL_RECOMMENDED' => '推荐的配置',
	'LBL_SYSTEM_STABILITY' => '系统稳定性配置',
	'LBL_SYSTEM_SECURITY' => '系统安全配置',
	'LBL_SECURITY_ADVISORIES_CHECKER' => '使用的库中的安全漏洞',
	'LBL_FILES_PERMISSIONS' => '文件/文件夹',
	'LBL_FILE' => '名称',
	'LBL_PATH' => '路径',
	'LBL_PERMISSION' => '权限',
	'LBL_TRUE_PERMISSION' => '允许的',
	'LBL_FAILED_PERMISSION' => '禁止的',
	'On' => '启用',
	'Off' => '关闭',
	'NOT RECOMMENDED' => '不推荐',
	'LBL_YETIFORCE_ENGINE' => 'YetiForce引擎',
	'LBL_CHECK_CONFIG' => 'RoundCube引擎',
	'LBL_MANDATORY' => '必填',
	'LBL_OPTIONAL' => '可选',
	'LBL_LIBRARY' => '支持库',
	'LBL_INSTALLED' => '已安装',
	'LBL_PDO_SUPPORT' => 'PDO',
	'LBL_OPEN_SSL' => 'openssl',
	'LBL_CURL' => 'cURL',
	'LBL_ZLIB_SUPPORT' => 'Zlib',
	'LBL_IMAP_SUPPORT' => 'IMAP',
	'LBL_GD_LIBRARY' => 'GD',
	'LBL_LDAP_LIBRARY' => 'LDAP',
	'LBL_PCRE_LIBRARY' => 'PCRE',
	'LBL_XML_LIBRARY' => 'XML',
	'LBL_JSON_LIBRARY' => 'JSON',
	'LBL_MYSQLND_LIBRARY' => 'MySQL自带的驱动(mysqlnd)',
	'LBL_SESSION_LIBRARY' => 'SESSION',
	'LBL_DOM_LIBRARY' => '文件对象模型',
	'LBL_MBSTRING_LIBRARY' => 'php_mbstring (需要mPDF)',
	'LBL_EXIF_LIBRARY' => 'Exif （改善上载文件的安全性）',
	'LBL_ZIP_ARCHIVE' => 'ZIP',
	'LBL_SPACE' => '容量',
	'LBL_SPACE_TOTAL' => '全部空间',
	'LBL_SPACE_FREE' => '可用空间',
	'LBL_SPACE_USED' => '已用空间',
	'LBL_VALUE' => '值',
	'LBL_PHPINI' => 'PHP设置',
	'LBL_LOG_FILE' => '日志',
	'LBL_CRM_DIR' => 'CRM本地文件夹',
	'LBL_SOAP_LIBRARY' => 'SOAP',
	'LBL_PHP_SAPI' => '服务器 API',
	'LBL_APCU_LIBRARY' => 'APCu',
	'LBL_OPCACHE_LIBRARY' => 'OPcache',
	'LBL_CRON_PHP' => '定时任务-PHP 版本',
	'LBL_CRON_PHPINI' => '定时任务-PHP 配置',
	'LBL_CRON_LOG_FILE' => '定时任务-错误日志',
	'LBL_CRON_PHP_SAPI' => '定时任务-API 服务器',
	'LBL_ENVIRONMENTAL_INFORMATION' => '环境信息',
	'LBL_OPERATING_SYSTEM' => '操作系统',
	'BTN_SERVER_SPEED_TEST' => '服务器速度测试',
	'LBL_LIB_NAME' => '库名称',
 	'LBL_VULNERABILITY_NAME' => '漏洞名称',
 	'LBL_VULNERABILITY_URL' => '漏洞地址',
	'HTTPS_HELP_TEXT' => 'SSL是web服务器和浏览器之间的建立加密链接的标准安全技术',
	'HTACCESS_HELP_TEXT' => '.htaccess文件可用于更改服务器软件配置，用来配置、启用/禁用附加服务。以便使YetiForceCRM能够对程序文件正确访问。',
	'PUBLIC_HTML_HELP_TEXT' => '我们建议您将系统只安装在public_html文件夹。这样，就不能直接从地址栏访问私有文件夹和文件，以提高数据安全性。',
	'SESSION_REGENERATE_HELP_TEXT' => '我们建议启用会话ID的重新生成，这个选项使得很难接管用户会话。 应该在主设置文件中进行更改。',
	'LBL_TMP_DIR' => '临时目录',
];
$jsLanguageStrings = [
	'JS_SPEED_TEST_START' => '检查速度...',
];
