<?php
/* ********************************************************************************
 *  Language     : 简体中文
 *  Version      : 4..2.514
 *  Author       : idercn.com | http://www.idercn.com
 *  Update Date  : 2017-12-22
  ********************************************************************************  
 * 此语言包版权如下所示：
 * 此文件内容受 vtigerCRM 的公共许可证1.0版保护，
 * 使用此文件表示您已默认遵守相关许可规定。
 * 您可以在遵守此许可证 "AS IS" 的基础上对软件进行分发。
 * 此语言包遵循 知识共享署名-非商业性使用-相同方式共享 2.5 中国大陆许可协议(Creative Commons) 2.5，
 * 大家可以免费下载使用，但请注明来源，并署名 · 非商业性使用 · 相同方式共享。
 * idercn无任何形式的担保，明示或暗示的保证。
 *+***********************************************************************************/
/* +***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * *********************************************************************************** */
$languageStrings = [
	'Conversion Rate' => '汇率',
	'Currency' => '币种',
	'Symbol' => '货币符号',
	'Currency Code' => '货币代码',
	'Currency Name' => '货币名称',
	'LBL_ADD_NEW_CURRENCY' => '添加新货币',
	'LBL_ADD_RECORD' => '添加货币',
	'LBL_CURRENCY_CODE' => '货币代码',
	'LBL_CURRENCY_NAME' => '货币名称',
	'LBL_CURRENCY_STATUS_DESC' => '勾选复选框启用货币',
	'LBL_CURRENCY_SYMBOL' => '货币符号',
	'LBL_CURRENT_CURRENCY' => '当前货币',
	'LBL_EDIT_CURRENCY' => '编辑货币',
	'LBL_ENTER_CONVERSION_RATE' => '输入汇率',
	'LBL_TRANSFER_CURRENCY' => '转换货币',
	//currency names
	'Afghanistan, Afghanis' => '阿富汗，阿富汗尼',
	'Albania, Leke' => '阿尔巴尼亚，列克',
	'Argentina, Pesos' => '阿根廷，比索',
	'Aruba, Guilders' => '阿鲁巴，盾',
	'Australia, Dollars' => '澳大利亚，澳大利亚元',
	'Azerbaijan, New Manats' => '阿塞拜疆，新马纳特',
	'Bahamas, Dollars' => '巴哈马群岛，巴哈马元（美元）',
	'Bahrain, Dinar' => '巴林，巴林第纳尔',
	'Barbados, Dollars' => '巴巴多斯，巴巴多斯元',
	'Belarus, Rubles' => '白俄罗斯，卢布',
	'Belize, Dollars' => '伯利兹，伯利兹元（美元）',
	'Bermuda, Dollars' => '百慕大，百慕大元（美元）',
	'Bolivia, Bolivianos' => '玻利维亚，玻利维亚诺',
	'Botswana, Pulas' => '博茨瓦纳，普拉',
	'Brazil, Reais' => '巴西《巴西雷亚尔',
	'Brunei Darussalam, Dollars' => '文莱达鲁萨兰国，元（美元）',
	'Bulgaria, Leva' => '保加利亚，列弗',
	'Cambodia, Riels' => '柬埔寨，瑞尔',
	'Canada, Dollars' => '加拿大，元',
	'Cayman Islands, Dollars' => '开曼群岛，元',
	'Chile, Pesos' => '智利，比索',
	'China, Yuan Renminbi' => '中国，人民币元', //Duplicated key-value pair
	'Colombia, Pesos' => '哥伦比亚，比索',
	'Convertible Marka' => '波黑，可自由兑换马克',
	'Costa Rica, Col?3n' => '哥斯达黎加，克朗',
	'Croatia, Kuna' => '克罗地亚，库纳',
	'Cuba, Pesos' => '古巴，比索',
	'Cyprus, Pounds' => '塞浦路斯，塞浦路斯镑',
	'Czech Republic, Koruny' => '捷克，克朗',
	'Denmark, Kroner' => '丹麦，克朗',
	'Dominican Republic, Pesos' => '多米尼加共和国，比索',
	'East Caribbean, Dollars' => '东加勒比海，元',
	'Egypt, Pounds' => '埃及，埃及磅',
	'El Salvador, Col?3n' => '萨尔瓦多，萨尔瓦多科朗',
	'England, Pounds' => '英格兰，磅',
	'Estonia, Krooni' => '爱沙尼亚，克伦尼',
	'Euro' => '欧元',
	'Falkland Islands, Pounds' => '福克兰群岛镑',
	'Fiji, Dollars' => '斐济，斐济元',
	'Ghana, Cedis' => '加纳，塞地',
	'Gibraltar, Pounds' => '直布罗陀镑',
	'Great Britain Pounds' => '大不列颠英镑',
	'Guatemala, Quetzales' => '危地马拉,格查尔',
	'Guernsey, Pounds' => '根西岛磅',
	'Guyana, Dollars' => '圭亚那,圭亚那元',
	'Honduras, Lempiras' => '洪都拉斯，伦皮拉',
	'Hungary, Forint' => '匈牙利，福林',
	'Iceland, Krona' => '冰岛，克朗',
	'India, Rupees' => '印度，卢比',
	'Indonesia, Rupiahs' => '印度尼西亚，卢比(盾)',
	'Iran, Rials' => '伊朗，里亚尔',
	'Isle of Man, Pounds' => '马恩岛，磅',
	'Israel, New Shekels' => '以色列，新谢客尔',
	'Jamaica, Dollars' => '牙买加元',
	'Japan, Yen' => '日本，日元',
	'Jersey, Pounds' => '泽西岛磅',
	'Jordan, Dinar' => '约旦，约旦第纳尔',
	'Kazakhstan, Tenge' => '哈萨克斯坦，腾格',
	'Kenya, Shilling' => '肯尼亚，肯尼亚先令',
	'Korea (North), Won' => '朝鲜，圆',
	'Korea (South), Won' => '韩国，圆',
	'Kyrgyzstan, Soms' => '吉尔吉斯斯坦，索姆',
	'Laos, Kips' => '老挝，基普',
	'Latvia, Lati' => '拉脱维亚，拉图',
	'Lebanon, Pounds' => '黎巴嫩，黎巴嫩镑',
	'Liberia, Dollars' => '利比里亚，元',
	'Lithuania, Litai' => '立陶宛，利泰',
	'LvHong Kong, Dollars ' => '香港，元 ',
	'Macedonia, Denars' => '马其顿，第纳尔',
	'MADAGASCAR, Malagasy Ariary' => '马达加斯加，马达加斯加阿里亚里',
	'Malawi, kwacha' => '马拉维，克瓦查',
	'Malaysia, Ringgits' => '马来西亚，林吉特(零吉)',
	'Malta, Liri' => '马耳他，里拉',
	'Mauritius, Rupees' => '毛里求斯，毛里求斯卢比',
	'Mexico, Pesos' => '墨西哥，墨西哥比索',
	'Mongolia, Tugriks' => '蒙古，图格里克',
	'Moroccan, Dirham' => '摩洛哥，迪拉姆',
	'Mozambique, Meticais' => '莫桑比克，梅蒂卡尔',
	'Namibia, Dollars' => '纳米比亚，纳米比亚元',
	'Nepal, Rupees' => '尼泊尔，卢比',
	'Netherlands Antilles, Guilders' => '荷属安地列斯群岛，荷兰盾',
	'New Zealand, Dollars' => '新西兰，新西兰元',
	'Nicaragua, Cordobas' => '尼加拉瓜，科多巴',
	'Nigeria, Nairas' => '尼日利亚，奈拉',
	'North Korea, Won' => '朝鲜，圆',
	'Norway, Krone' => '挪威，克朗',
	'Oman, Rials' => '阿曼，里亚尔',
	'Pakistan, Rupees' => '巴基斯坦，卢比',
	'Panama, Balboa' => '巴拿马，巴尔博亚',
	'Paraguay, Guarani' => '巴拉圭，瓜拉尼',
	'Peru, Nuevos Soles' => '秘鲁，索尔',
	'Philippines, Pesos' => '菲律宾，比索',
	'Poland, Zlotych' => '波兰，兹罗提',
	'Qatar, Rials' => '卡塔尔，里亚尔',
	'Romania, New Lei' => '罗马尼亚，新列伊',
	'Russia, Rubles' => '俄罗斯，卢布',
	'Saint Helena, Pounds' => '圣海伦娜，磅',
	'Saudi Arabia, Riyals' => '沙特阿拉伯，里亚尔',
	'Serbia, Dinars' => '塞尔维亚，第纳尔',
	'Seychelles, Rupees' => '塞舌尔，卢比',
	'Singapore, Dollars' => '新加坡，元',
	'Solomon Islands, Dollars' => '索罗门群岛，所罗门群岛元',
	'Somalia, Shillings' => '索马里，先令',
	'South Africa, Rand' => '南非，兰特',
	'South Korea, Won' => '韩国，圆',
	'Sri Lanka, Rupees' => '斯里兰卡，卢比',
	'Suriname, Dollars' => '苏里南，苏里南元',
	'Sweden, Kronor' => '瑞典，克朗',
	'Switzerland Francs' => '瑞士，法郎',
	'Switzerland, Francs' => '瑞士，法郎',
	'Syria, Pounds' => '叙利亚，磅',
	'Taiwan, New Dollars' => '台湾，新台币',
	'Thailand, Baht' => '泰国，泰铢',
	'Trinidad and Tobago, Dollars' => '特立尼达和多巴哥元',
	'Tunisian, Dinar' => '突尼斯，第纳尔',
	'Turkey, Liras' => '土耳其，里拉',
	'Turkey, New Lira' => '土耳其，里拉',
	'Tuvalu, Dollars' => '图瓦卢，图瓦卢元',
	'Ukraine, Hryvnia' => '乌克兰，格里夫纳',
	'United Arab Emirates, Dirham' => '阿拉伯联合酋长国，阿联酋迪拉姆',
	'United Kingdom, Pounds' => '英国，英镑',
	'United Republic of Tanzania, Shilling' => '坦桑尼亚联合共和国，先令',
	'Uruguay, Pesos' => '乌拉圭，比索',
	'USA, Dollars' => '美国，美元',
	'Uzbekistan, Sums' => '乌兹别克斯坦，苏姆',
	'Venezuela, Bolivares Fuertes' => '委内瑞拉，博利瓦',
	'Vietnam, Dong' => '越南，越南盾',
	'Yemen, Rials' => '阿拉伯也门 也门里亚尔',
	'Zambia, Kwacha' => '赞比亚，赞比亚克瓦查',
	'Zimbabwe Dollars' => '津巴布韦，津巴布韦元',
	'Active' => '启用',
	'Inactive' => '禁用',
];

$jsLanguageStrings = [
	'JS_CURRENCY_DELETED_SUCCESSFULLY' => '货币已删除。',
	'JS_CURRENCY_DETAILS_SAVED' => '货币信息已保存。',
];
