<?php
/* ********************************************************************************
 *  Language     : 简体中文
 *  Version      : 3.2.0
 *  Author       : idercn.com | http://www.idercn.com
 *  Update Date  : 2016-09-01
  ********************************************************************************  
 * 此语言包版权如下所示：
 * 此文件内容受 vtigerCRM 的公共许可证1.0版保护，
 * 使用此文件表示您已默认遵守相关许可规定。
 * 您可以在遵守此许可证 "AS IS" 的基础上对软件进行分发。
 * 此语言包遵循 知识共享署名-非商业性使用-相同方式共享 2.5 中国大陆许可协议(Creative Commons) 2.5，
 * 大家可以免费下载使用，但请注明来源，并署名 · 非商业性使用 · 相同方式共享。
 * idercn无任何形式的担保，明示或暗示的保证。
 *+***********************************************************************************/
/**
 * Polish language
 * @package YetiForce.Language
 * @license licenses/License.html
 * @author Maciej Stencel <m.stencel@yetiforce.com>
 * @author Mariusz Krzaczkowski <m.krzaczkowski@yetiforce.com>
 */
$languageStrings = [
	'LBL_PDF' => 'PDF',
	'LBL_PDF_DESCRIPTION' => 'PDF模板配置的测试版本',
	'LBL_CREATING_PDF' => '新建PDF模板',
	'LBL_EDITING_PDF' => '编辑PDF模板',
	'LBL_ENTER_BASIC_DETAILS' => '请输入文档描述',
	'LBL_FINISH' => '完成',
	'LBL_NEW' => '新建',
	'LBL_NEXT' => '下一个',
	'LBL_STEP_N' => '阶段 %d',
	'LBL_PDF_TEMPLATE' => 'PDF模板',
	'LBL_DOCUMENT_DESCRIPTION' => '文档描述',
	'LBL_DOCUMENT_SETTINGS' => '文档设置',
	'LBL_DOCUMENT_HEADER' => '标题内容',
	'LBL_DOCUMENT_BODY' => '主要内容',
	'LBL_DOCUMENT_FOOTER' => '页脚内容',
	'LBL_DOCUMENT_EXCEPTIONS' => '例外',
	'LBL_DOCUMENT_PERMISSIONS' => '许可',
	'LBL_DOCUMENT_WATERMARK' => '水印',
	'Module' => '模块',
	'active' => '激活',
	'inactive' => '未启用',
	'LBL_PRIMARY_NAME' => '主要名称',
	'LBL_SECONDARY_NAME' => '附加名称',
	'LBL_FOLDER_NAME' => '文件夹名称',
	'LBL_SELECT_MODULE' => '选择模块',
	'LBL_META_TITLE' => '标题',
	'LBL_META_AUTHOR' => '作者',
	'LBL_META_CREATOR' => '编写者',
	'LBL_META_SUBJECT' => '标题',
	'LBL_META_KEYWORDS' => '关键词',
	'PLL_COMPANY_NAME' => '公司名称',
	'PLL_USER_CREATING' => '生成此文档的用户',
	'LBL_METATAGS' => '自动meta标签',
	'LBL_PAGE_FORMAT' => '文档格式',
	'LBL_MAIN_MARGIN' => '自动主页边距',
	'LBL_TOP' => '顶部',
	'LBL_RIGHT' => '右侧',
	'LBL_BOTTOM' => '底部',
	'LBL_LEFT' => '左',
	'LBL_TOP_IN_MILIMETERS' => '顶部部空白（mm）',
	'LBL_BOTTOM_IN_MILIMETERS' => '底部空白（mm）',
	'LBL_LEFT_IN_MILIMETERS' => '左侧空白（mm）',
	'LBL_RIGHT_IN_MILIMETERS' => '右侧空白（mm）',
	'LBL_PAGE_ORIENTATION' => '文档方向',
	'PLL_LANDSCAPE' => '横向',
	'PLL_PORTRAIT' => '纵向',
	'LBL_LANGUAGE_CHOICE' => '语言选项',
	'LBL_FILENAME' => '生成文件的名称',
	'LBL_VISIBILITY' => '可用在视图',
	'PLL_LISTVIEW' => '列表',
	'PLL_DETAILVIEW' => '记录',
	'LBL_DEFAULT_TPL' => '默认情况下选中',
	'LBL_DOCUMENT_SETTINGS_DETAILS' => '文档设置',
	'LBL_MAIN_MODULE_FIELDS' => '主要模块字段',
	'LBL_RELATED_MODULES' => '相关的模块',
	'LBL_RELATED_MODULES_FIELDS' => '相关的模块字段',
	'LBL_SPECIAL_FUNCTIONS' => '特殊功能',
	'LBL_COMPANY_FIELDS' => '公司信息',
	'LBL_LABEL' => '标签',
	'LBL_FIELD' => '值',
	'LBL_HEADER_DETAILS' => '编辑页眉',
	'LBL_HEADER_CONTENT' => '页眉',
	'LBL_SET_VALUE' => '设置值',
	'LBL_RAW_TEXT' => '纯文本',
	'LBL_USE_FIELD' => '使用字段',
	'LBL_USE_FUNCTION' => '使用功能',
	'LBL_EXAMPLE_EXPRESSION' => '表达式',
	'LBL_EXPRESSION' => '表达式',
	'LBL_ANNUAL_REVENUE' => '年度营收',
	'LBL_EXPRESSION_EXAMPLE2' => "如果 邮寄国家为'印度'，联系人格式(名字，姓氏)，否则联系人格式为(姓氏，名字)",
	'LBL_EXAMPLE_FIELD_NAME' => '字段',
	'LBL_NOTIFY_OWNER' => '通知主人',
	'LBL_WATERMARK_DETAILS' => '编辑水印',
	'LBL_WATERMARK_TYPE' => '水印类型',
	'LBL_WATERMARK_TEXT' => '水印内容',
	'LBL_WATERMARK_IMAGE' => '水印图片',
	'LBL_DELETE_WM' => '移除水印',
	'LBL_UPLOAD_WM' => '上传水印',
	'LBL_BODY_DETAILS' => '编辑文档内容',
	'LBL_FOOTER_DETAILS' => '编辑页脚',
	'LBL_MAIN_MODULE' => '主要模块',
	'LBL_WATERMARK_SIZE' => '字号',
	'LBL_WATERMARK_ANGLE' => '角度(以度为单位)',
	'LBL_IMPORT_TEMPLATE' => '导入模板',
	'LBL_UPLOAD_ERROR' => '导入PDF模板的XML文件失败！!',
	'LBL_UPLOAD_OK' => '模板文件导入成功.',
	'LBL_IMPORT_VIEW' => 'PDF模板导入',
	'LBL_TEMPLATE_XML' => 'XML文件',
	'LBL_UPLOAD_TEMPLATE' => '导入',
	'LBL_GO_TO_TEMPLATE' => '单击进入导入模板.',
	'LBL_RETURN' => '返回',
	'LBL_PERMISSIONS_DETAILS' => '许可',
	'LBL_INSERT' => '插入',
	'PAGENO' => '页数',
	'PAGENUM' => '页码',
	'LBL_HEADER_HEIGHT' => '头部空白',
	'LBL_FOOTER_HEIGHT' => '页脚空白',
	'LBL_HEADER_IN_MILIMETERS' => '头部空白（从顶部开始，mm）',
	'LBL_FOOTER_IN_MILIMETERS' => '页脚空白（从底部开始，mm）',
	// page format names
	'4A0' => '4A0',
	'2A0' => '2A0',
	'A0' => 'A0',
	'A1' => 'A1',
	'A2' => 'A2',
	'A3' => 'A3',
	'A4' => 'A4',
	'A5' => 'A5',
	'A6' => 'A6',
	'A7' => 'A7',
	'A8' => 'A8',
	'A9' => 'A9',
	'A10' => 'A10',
	'B0' => 'B0',
	'B1' => 'B1',
	'B2' => 'B2',
	'B3' => 'B3',
	'B4' => 'B4',
	'B5' => 'B5',
	'B6' => 'B6',
	'B7' => 'B7',
	'B8' => 'B8',
	'B9' => 'B9',
	'B10' => 'B10',
	'C0' => 'C0',
	'C1' => 'C1',
	'C2' => 'C2',
	'C3' => 'C3',
	'C4' => 'C4',
	'C5' => 'C5',
	'C6' => 'C6',
	'C7' => 'C7',
	'C8' => 'C8',
	'C9' => 'C9',
	'C10' => 'C10',
	'RA0' => 'RA0',
	'RA1' => 'RA1',
	'RA2' => 'RA2',
	'RA3' => 'RA3',
	'RA4' => 'RA4',
	'SRA0' => 'SRA0',
	'SRA1' => 'SRA1',
	'SRA2' => 'SRA2',
	'SRA3' => 'SRA3',
	'SRA4' => 'SRA4',
	'LETTER' => '信',
	'LEGAL' => '法律',
	'LEDGER' => '分类帐',
	'TABLOID' => '摘要',
	'EXECUTIVE' => '执行经理',
	'FOLIO' => '对开',
	'B' => 'B',
	'A' => 'A',
	'DEMY' => '纸张尺寸',
	'ROYAL' => '皇家'
];
$jsLanguageStrings = [
	'JS_PDF_SAVED_SUCCESSFULLY' => 'PDF模板保存.',
	'JS_NOTIFY_COPY_TEXT' => '已复制到剪贴板',
	'JS_NOTIFY_COPY_TITLE' => '文本',
	'JS_PDF_TEMPLATE_EXPORTED' => 'PDF模板文件导出成功.',
	'JS_RECALCULATING' => '重新计算权限...',
];
