<?php
/* ********************************************************************************
 *  Language     : 简体中文
 *  Version      : 3.2.0
 *  Author       : idercn.com | http://www.idercn.com
 *  Update Date  : 2016-09-01
  ********************************************************************************  
 * 此语言包版权如下所示：
 * 此文件内容受 vtigerCRM 的公共许可证1.0版保护，
 * 使用此文件表示您已默认遵守相关许可规定。
 * 您可以在遵守此许可证 "AS IS" 的基础上对软件进行分发。
 * 此语言包遵循 知识共享署名-非商业性使用-相同方式共享 2.5 中国大陆许可协议(Creative Commons) 2.5，
 * 大家可以免费下载使用，但请注明来源，并署名 · 非商业性使用 · 相同方式共享。
 * idercn无任何形式的担保，明示或暗示的保证。
 *+***********************************************************************************/
/* +***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * Contributor(s): YetiForce.com
 * ********************************************************************************** */
$languageStrings = [
	'Activity Type' => '事件类型',
	'Call' => '电话',
	'Completed' => '已完成',
	'Deferred' => '延期',
	'first' => '第一个',
	'ICAL_FORMAT' => 'iCal 格式',
	'last' => '后',
	'LBL_ACTIVITY_TYPES' => '事件类型',
	'LBL_ADD_CALENDAR_VIEW' => '添加日历视图',
	'LBL_ADDED_CALENDARS' => '新增日程',
	'LBL_ADD_EVENT' => '添加事件',
	'LBL_ADD_TASK' => '添加待办',
	'LBL_CALENDAR_SETTINGS' => '日程设置',
	'LBL_CALENDAR_SHARING' => '日历共享',
	'LBL_CALENDAR_VIEW' => '日程',
	'LBL_CALENDAR_LIST' => '记录列表（来自日历）',
	'LBL_CALL' => '电话',
	'LBL_CHANGE_OWNER' => '更改负责人',
	'LBL_CONTACTS_BIRTH_DAY' => '出生日期',
	'LBL_CONTACTS_SUPPORT_END_DATE' => '支持结束日期',
	'LBL_DAY0' => '星期天',
	'LBL_DAY1' => '星期一',
	'LBL_DAY2' => '星期二',
	'LBL_DAY3' => '星期三',
	'LBL_DAY4' => '星期四',
	'LBL_DAY5' => '星期五',
	'LBL_DAY6' => '星期六',
	'LBL_DAY_OF_THE_MONTH' => '天#本月',
	'LBL_DEFAULT_EVENT_DURATION' => '默认事件持续时间',
	'LBL_DEFAULT_STATUS_TYPE' => '默认的状态和类型',
	'LBL_DELETE_CALENDAR' => '删除日程',
	'LBL_EDIT_COLOR' => '编辑颜色',
	'LBL_EDITING_CALENDAR_VIEW' => '遍',
	'LBL_EVENT' => '事件',
	'LBL_EVENT_INFORMATION' => '事件细节',
	'LBL_EVENT_OR_TASK' => '事件 / 待办',
	'LBL_EVENTS' => '事件',
	'LBL_FINISH' => '完成',
	'LBL_IMPORT_RECORDS' => '导入记录',
	'LBL_LAST_IMPORT_UNDONE' => '你上次的导入未完成',
	'LBL_MINUTES' => '分钟',
	'LBL_ON' => 'on',
	'LBL_OTHER_EVENTS' => '其它事件',
	'LBL_RECORDS_LIST' => '日历列表', //Duplicated key-value pair
	'LBL_RESULT' => '结果',
	'LBL_SELECT_ACTIVITY_TYPE' => '选择活动类型',
	'LBL_SELECT_CALENDAR_COLOR' => '选择日历颜色',
	'LBL_SELECT_USER_CALENDAR' => '选择用户日历',
	'LBL_SELECT_USERS' => '选择用户',
	'LBL_SHARED_CALENDAR' => '共享的日程',
	'LBL_STATUS' => '状态',
	'LBL_TASK_INFORMATION' => '待办事项细节',
	'LBL_TASKS' => '待办事项',
	'LBL_TASK' => '待办事项',
	'LBL_TODOS' => '待办事项',
	'LBL_TOTAL_EVENTS_IMPORTED' => '成功导入的事件数 ',
	'LBL_TOTAL_EVENTS_SKIPPED' => '因缺少所需要的字段跳过的事件数 ',
	'LBL_TOTAL_TASKS_IMPORTED' => '成功导入的任务数 ',
	'LBL_TOTAL_TASKS_SKIPPED' => '因缺少所需要的字段跳过的任务数 ',
	'LBL_TYPE' => '类型',
	'LBL_UNDO_LAST_IMPORT' => '撤消最后导入',
	'Location' => '地点',
	'Medium' => '中',
	'Meeting' => '会议',
	'Not Started' => '尚未开始',
	'Pending Input' => '待输入',
	'Cancelled' => '已取消',
	'Send Notification' => '发送通知',
	'SINGLE_Calendar' => '待办事项',
	'SINGLE_Events' => '事件',
	'Start Date & Time' => '开始日期和时间',
	'End Date & Time' => '结束日期及时间',
	'Start Date &amp; Time' => '开始日期和时间',
	'End Date &amp; Time' => '结束日期及时间',
	'End Date' => '结束日期',
	'End Time' => '结束时间',
	'Subject' => '标题',
	'Tasks' => '待办事项',
	'Task' => '待办事项',
	'Held' => '已进行',
	'Not Held' => '未进行',
	'All day' => '全天',
	'LBL_STATE' => '显示为',
	'PLL_OPAQUE' => '忙',
	'PLL_TRANSPARENT' => '闲',
	'Sunday' => '星期天',
	'Monday' => '星期一',
	'Tuesday' => '星期二',
	'Wednesday' => '星期三',
	'Thursday' => '星期四',
	'Friday' => '星期五',
	'Saturday' => '星期六',
	'Private' => '私人',
	'Selected Users' => '选定的用户',
	'Send Reminder' => '发送提醒',
	'Time Start' => '开始时间',
	'Start Time' => '开始时间',
	'Recurrence' => '重复周期',
	'Visibility' => '公开程度',
	'Duration' => '工期',
	'Duration Minutes' => '持续时间（分钟）',
	'No Time' => '没有时间',
	'Recurrence' => '重复周期',
	'LBL_NO_DESCRIPTION' => '没有说明',
	'LBL_IMPORT_ICS_ERROR_NO_RECORD' => '错误的 ICS 文件',
	'LBL_IMPORT_ICS_SUCCESS' => '已添加到日历条目',
	'LBL_SHITF_TASK_SHOW' => '显示或隐藏活动类型 ︰ 任务',
	'LBL_SHITF_MEETING_SHOW' => '显示或隐藏活动类型 ︰ 摊派',
	'LBL_SHITF_CALL_SHOW' => '显示或隐藏活动类型 ︰ 用户',
	'LBL_SHIFT_USER_SHOW' => '显示或隐藏用户',
	'Activity Type_BLOCK_SHIFT' => '显示或隐藏活动块类型',
	'LBL_USERS_BLOCK_SHIFT' => '显示或隐藏用户块类型',
	'LBL_GROUPS_BLOCK_SHIFT' => '显示或隐藏组块类型',
	'LBL_SHIFT_BLOCK' => '显示或隐藏块',
	'LBL_ON_SWITCH' => '打开',
	'LBL_OFF_SWITCH' => '关闭',
	'LBL_FOLLOWUP' => '相关的事件',
	'PLL_PLANNED' => '已计划',
	'PLL_IN_REALIZATION' => '将要实现',
	'PLL_OVERDUE' => '过期',
	'PLL_POSTPONED' => '延迟',
	'PLL_CANCELLED' => '已取消',
	'PLL_COMPLETED' => '已完成',
	'LBL_RECURRENCE_INFORMATION' => '重复信息',
	'LBL_RELATED_TO' => '相关于',
	'LBL_NO_AVAILABLE_ACTIONS' => '没有可用的操作',
	'LBL_CALENDAR_FILTERS' => '筛选',
	'LBL_AUTO_FILL_DESCRIPTION' => '根据可用的第一天填充开始日期',
	'LBL_CACHE_SELECTED_FILTERS' => '日历中的标准视图已更改。单击"清除视图"以将其清除.',
	'LBL_CACHE_CLEAR' => '清除视同',
	'LBL_PROCESS' => '处理',
];

$jsLanguageStrings = [
	'JS_CALENDAR_VIEW_ADDED_SUCCESSFULLY' => '已成功添加的日历视图',
	'JS_CALENDAR_VIEW_COLOR_UPDATED_SUCCESSFULLY' => '已成功更新的日历视图颜色',
	'JS_CALENDAR_VIEW_DELETE_CONFIRMATION' => '您确定要删除此日历视图吗？ ?',
	'JS_CALENDAR_VIEW_DELETED_SUCCESSFULLY' => '已成功删除的日历视图',
	'JS_EDIT_CALENDAR' => '编辑日历',
	'JS_NO_CALENDAR_VIEWS_TO_ADD' => '没有添加日历视图',
	'JS_NO_DELETE_PERMISSION' => '您没有权限删除日历条目.',
	'JS_NO_EDIT_PERMISSION' => '您没有权限修改日历条目.',
	'JS_TASK_IS_SUCCESSFULLY_ADDED_TO_YOUR_CALENDAR' => '待办事项成功添加到您的日历',
	'JS_RECORD_DELETED' => '已成功删除的日历条目',
	'JS_START_DATE' => '开始日期',
	'JS_END_DATE' => '结束日期',
	'JS_LOCATION' => '地点',
	'JS_PRIORITY' => '优先级',
	'JS_STATUS' => '状态',
	'JS_Activity Type' => '事件类型',
	'JS_Not Started' => '尚未开始',
	'JS_In Progress' => '正在进行',
	'JS_Completed' => '已完成',
	'JS_Pending Input' => '待输入',
	'JS_Deferred' => '延期',
	'JS_Cancelled' => '已取消',
	'JS_Call' => '电话',
	'JS_Held' => '已进行',
	'JS_Not Held' => '未进行',
	'JS_Meeting' => '会议',
	'JS_Task' => '任务',
	'JS_Low' => '低',
	'JS_Normal' => '一般',
	'JS_Medium' => '中',
	'JS_High' => '高',
	'JS_ACCOUNTS' => '客户',
	'JS_STATE' => '显示为',
	'JS_VISIBILITY' => '公开程度',
	'PLL_OPAQUE' => '忙',
	'PLL_TRANSPARENT' => '闲',
	'JS_Private' => '私人',
	'JS_Public' => '公共',
	'Mobile Call' => '手机通话',
	'JS_CHANGE_ACTIVITY_TIME' => '将状态更改为 ︰ 用于处理或历史',
	'JS_ASSIGNED_TO' => '分配给',
	'JS_SWITCHING_DAYS' => '转换天 ',
	'JS_ALL' => '全部',
	'JS_WORK_DAYS' => '工作天数',
];
