<?php
/* ********************************************************************************
 *  Language     : 简体中文
 *  Version      : 3.2.0
 *  Author       : idercn.com | http://www.idercn.com
 *  Update Date  : 2016-09-01
  ********************************************************************************  
 * 此语言包版权如下所示：
 * 此文件内容受 vtigerCRM 的公共许可证1.0版保护，
 * 使用此文件表示您已默认遵守相关许可规定。
 * 您可以在遵守此许可证 "AS IS" 的基础上对软件进行分发。
 * 此语言包遵循 知识共享署名-非商业性使用-相同方式共享 2.5 中国大陆许可协议(Creative Commons) 2.5，
 * 大家可以免费下载使用，但请注明来源，并署名 · 非商业性使用 · 相同方式共享。
 * idercn无任何形式的担保，明示或暗示的保证。
 *+***********************************************************************************/
/* {[The file is published on the basis of YetiForce Public License that can be found in the following directory: licenses/License.html]} */
$languageStrings = [
	'OSSMailScanner' => '邮件扫描程序',
	'OSSMailScanner_manual' => '邮件扫描程序',
	'E-mail Accounts' => '电子邮件帐户',
	'Action' => '操作',
	'Desc' => '描述',
	'username' => '用户名',
	'mail_host' => '服务器',
	'language' => '语言',
	'nazwa' => '函数名称',
	'katalog' => '文件路径',
	'opis' => '描述',
	'CreatedEmail' => '创建电子邮件消息',
	'BindContacts' => '关联到联系人',
	'BindAccounts' => '关联到客户',
	'BindLeads' => '关联到潜在客户',
	'BindSSalesProcesses' => '关联到销售机会',
	'BindHelpDesk' => '关联到支持人员',
	'BindProject' => '关联到项目',
	'BindServiceContracts' => '关联到服务合同',
	'BindCompetition' => '关联到竞争',
	'BindOSSEmployees' => '关联到员工',
	'BindPartners' => '与合作伙伴关联',
	'BindVendors' => '与供应商关联',
	'BindCampaigns' => '关联到营销活动',
	'created_Accounts' => '创建帐户',
	'created_Contacts' => '创建联系人',
	'CreatedHelpDesk' => '创建服务支持',
	'update_HelpDesk' => '更新服务支持',
	'update_Accounts' => '更新客户',
	'update_Contacts' => '更新联系人',
	'desc_CreatedEmail' => 'CRM中添加电子邮件消息.',
	'desc_BindCompetition' => '创建“包含电子邮件地址的竞争记录”和“邮件消息”之间的关联.',
	'desc_BindOSSEmployees' => '创建电子邮件消息与包含电子邮件地址的员工之间的联系.',
	'desc_BindPartners' => '创建电子邮件消息与包含电子邮件地址的合作伙伴之间的联系.',
	'desc_BindVendors' => '创建电子邮件消息与包含电子邮件地址的供应商之间的联系.',
	'desc_BindContacts' => '创建电子邮件消息与包含电子邮件地址的联系人之间的联系.',
	'desc_BindAccounts' => '创建电子邮件消息与包含此电子邮件地址的客户之间的联系.',
	'desc_BindLeads' => '创建电子邮件消息与包含此电子邮件地址的潜在客户之间的联系.',
	'desc_BindSSalesProcesses' => '与基于前缀号码的主体的潜在记录创建关系的电子邮件消息.',
	'desc_BindHelpDesk' => '与基于前缀号码的主题的帮助台记录创建关系的电子邮件消息.',
	'desc_BindProject' => '与基于前缀号码的主题的项目记录创建关系的电子邮件消息.',
	'desc_BindServiceContracts' => '与基于帐户与电子邮件关联的项目记录创建关系的电子邮件消息.',
	'desc_BindCampaigns' => '与基于前缀号码的主体的市场活动记录创建关系的电子邮件消息.',
	'desc_created_Accounts' => '创建帐户详情',
	'desc_created_Contacts' => '创建联系人详情',
	'desc_CreatedHelpDesk' => '创建服务支持详情.',
	'desc_update_HelpDesk' => '更新服务支持详情',
	'desc_update_Accounts' => '更新帐户详情',
	'desc_update_Contacts' => '更新联系人详情',
	'Folder configuration' => '文件夹配置',
	'Actions' => '操作',
	'MailView config' => '配置',
	'General Configuration' => '常规配置',
	'Search email configuration' => '搜索电子邮件配置',
	'Alert_no_module_title' => '本模块未找到或处于关闭状态.',
	'Alert_no_module_desc' => '扫描模块需要您安装和计划外发邮件模块，请检查此模块是否安装，如果没有安装，您需要安装它.',
	'Alert_no_accounts_title' => '找不到的电子邮件帐户',
	'Alert_no_accounts_desc' => '要激活电子邮件扫描程序，您需要第一次登录到 OSSMail 模块中的电子邮件帐户.',
	'Alert_info_tab_actions' => '邮件文件的操作位于: 模块/OSSMailScanner/scanneractions/',
	'Alert_no_email_acconts' => '找不到的电子邮件帐户',
	'Alert_no_email_acconts_desc' => '若要配置文件夹，您需要登录到空房邮箱的第一次.',
	'Alert_info_tab_email_search' => '选择将被用来搜索收件人的电子邮件消息的字段.',
	'Alert_info_tab_folder' => '选择下载电子邮件时将被扫描的文件夹. ',
	'Alert_info_tab_accounts' => '选择何种行动应触发的个人电子邮件帐户.',
	'Alert_info_tab_record_numbering' => '前缀用来关联邮件与CRM的其他数据。只有设置了前缀的模块才能与邮件关联，前缀不能为空.',
	'Alert_active_cron' => '在附表中的不活动任务.',
	'Alert_active_cron_desc' => '在模块扫描计划中找不到任务，或任务之一处于禁用状态。有所有的扫描模块激活，电子邮件扫描程序才能正常工作。（MailScannerAction，MailScannerVerification）',
	'Alert_active_crontime' => '不正确频率的进度要求.',
	'Alert_active_crontime_desc' => '"MailScannerAction"任务的调用频率应至少两次的频率"MailScannerVerification"任务',
	'All_folder' => '全部',
	'Received' => '收到',
	'Sent' => '已发送',
	'Spam' => '垃圾邮件',
	'Trash' => '二进制',
	'Function_list' => '函数的列表',
	'Folder_list' => '文件夹列表',
	'Record Numbering' => '前缀',
	'ConfigCustomRecordNumbering' => '编号的配置',
	'Module' => '模块',
	'Alert_scanner_not_work' => '没有前缀，邮件扫描不工作',
	'Roundcube config' => '总是配置',
	'LBL_SAVE' => '保存配置',
	'Spam' => '垃圾邮件',
	'Spam' => '垃圾邮件',
	'JS_save_info' => '保存的操作列表',
	'JS_saveuser_info' => '用户已保存',
	'LBL_SAVE_FOLDER_INFO' => '保存的文件夹列表',
	'JS_save_fields_info' => '保存字段列表',
	'JS_save_config_info' => '配置已保存',
	'Cron' => '计划任务',
	'RunCron' => '开始手动扫描',
	'startTime' => '开始时间',
	'endTime' => '结束时间',
	'status' => '状态',
	'account' => '客户',
	'action' => '操作',
	'folder' => '文件夹',
	'count' => '电子邮件检查',
	'who' => '用户',
	'OK' => '好',
	'In progress' => '在实现',
	'Error' => '错误',
	'email_to_notify' => '通知电子邮件',
	'time_to_notify' => '通知（分钟）的时间',
	'StopCron' => '手动停止扫描',
	'Manually stopped' => '手动停止',
	'stop_user' => '停止扫描',
	'Email_Subject' => '通知:计划任务运行时间太长',
	'Email_Body' => '你好<br><br>计划任务运行时间太长，检查邮件系统是否工作正常。<br><br>管理员',
	'Email_FromName' => 'YetiForce 计划任何',
	'JS_info_restart_ok' => '计划任务解锁',
	'permissions_all' => '对所有可见',
	'permissions_vtiger' => '基于 vtiger 权限',
	'permissions_user_email' => '基于用户地址',
	'Permissions' => '许可',
	'User' => '用户',
	'None' => '选择用户',
	'User list' => '用户列表',
	'identities_name' => '标识名称',
	'identities_adress' => '标识地址',
	'identities_del' => '删除标识',
	'show_identities' => '显示标识',
	'IMAP_ERROR' => '无法连接到电子邮件服务器',
	'ERROR_ACTIVE_CRON' => '无法打开扫描因为计划任务是当前处于活动状态.',
	'Change ticket status' => '服务单状态更改',
	'Change_ticket_status' => '更新服务单状态',
	'Alert_info_conftab_change_ticket_status' => '此选项允许将机票服务单状态更改为"回复"，当邮件扫描器发现从服务单的客户发来一封电子邮件时.',
	'Action_DisabledModule' => '禁用模块',
	'Action_EnabledModule' => '启用模块',
	'Action_UpdateModule' => '更新模块',
	'Action_InstallModule' => '安装模块',
	'Action_Bind' => '标记为绑定',
	'Action_CronMailScanner' => '计划任务-电子邮件扫描',
	'Action_CronBind' => '计划任务-绑定',
	'Action_ChangeType' => '更改邮件类型',
	'AccontDeleteOK' => '已删除的帐户',
	'No' => '否//Yes or No',
	'LBL_MAIL_LOGS' => '邮件日志',
	'Group list' => '组列表',
	'LBL_ACTIVE_MAIL' => '激活',
	'LBL_INACTIVE_MAIL' => '未启用',
	'LBL_EXCEPTIONS' => '例外',
	'LBL_EXCEPTIONS_CREATING_EMAIL' => '执行创建邮件时行动省略地址',
	'LBL_EXCEPTIONS_CREATING_TICKET' => '执行创建服务单时行动省略地址',
	'LBL_WRITE_AND_ENTER' => '输入的地址并按 enter 键',
	'ERR_NO_CONFIGURATION_FOLDERS' => '没有文件夹配置',
	'LBL_SHOW_ACCOUNT_DETAILS' => '显示客户细节',
	'LBL_EDIT_FOLDER_ACCOUNT' => '编辑文件夹',
	'LBL_ALERT_EDIT_FOLDER' => '选择文件夹，删除它们然后重新添加，将会重新启动他们的邮件扫描.',
	'LBL_DELETE_ACCOUNT' => '删除客户',
];
