<?php
/* +***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * Contributor(s): YetiForce.com
 * *********************************************************************************** */
$languageStrings = [
	'PRIMARY_MODULE' => '主模块',
	'Report Name' => '报表名称',
	'Reports' => '报表',
	'SINGLE_Reports' => '报表',
	'LBL_ADD_FOLDER' => '添加文件夹',
	'LBL_ADD_NEW_FOLDER' => '创建新文件夹',
	'LBL_ADD_RECORD' => '添加报表',
	'LBL_ALL_REPORTS' => '所有报表',
	'LBL_ASCENDING' => '升序',
	'LBL_AT_TIME' => '时间',
	'LBL_AVERAGE' => '一般',
	'LBL_AVG' => '平均',
	'LBL_CALCULATION_CONVERSION_MESSAGE' => '计算价格依据系统设定的基础货币',
	'LBL_CALCULATIONS' => '价格计算',
	'LBL_CHOOSE_DATE' => '选择日期',
	'LBL_COLUMNS' => '列',
	'LBL_CREATING_REPORT' => '创建报表',
	'LBL_CUSTOMIZE' => '编辑',
	'LBL_DAILY' => '每天',
	'LBL_DENIED_REPORTS' => '被拒绝报表',
	'LBL_DESCENDING' => '降序',
	'LBL_DESCRIPTION' => '描述',
	'LBL_DUPLICATES_EXIST' => '报表名称已经存在',
	'LBL_EDITING_REPORT' => '编辑报表',
	'LBL_EXCEEDING_MAXIMUM_LIMIT' => '超过最大限值',
	'LBL_FIELD_NAMES' => '字段名称',
	'LBL_FILTERS' => '筛选视图',
	'LBL_FOLDER_CAN_NOT_BE_DELETED' => '此文件夹不能被删除',
	'LBL_FOLDER_DESCRIPTION' => '文件夹描述',
	'LBL_FOLDER_NAME' => '文件夹名称',
	'LBL_FOLDER_NOT_EMPTY' => '文件夹不是空的',
	'LBL_FOLDERS' => '文件夹',
	'LBL_FOLDERS_LIST' => '文件夹列表',
	'LBL_GENERATE_NOW' => '现在生成',
	'LBL_GENERATE_REPORT' => '生成报表',
	'LBL_GROUP_BY' => '分组',
	'LBL_HIGHEST_VALUE' => '最高值',
	'LBL_LIMIT_EXCEEDED' => '只能显示1000+条记录。使用CSV或Excel导出查看所有记录',
	'LBL_LOWEST_VALUE' => '最低值',
	'LBL_MAX' => '最大',
	'LBL_MIN' => '最小',
	'LBL_MONTHLY_BY_DATE' => '每月“日”视图',
	'LBL_MORE_RECORDS_TXT' => '只能显示1000条记录。请导出以查看所有记录',
	'LBL_MOVE_REPORT' => '移动报表',
	'LBL_NEXT' => '下一个',
	'LBL_NEXT_TRIGGER_TIME' => '下一次触发时间',
	'LBL_NO_OF_RECORDS' => '报表数量',
	'LBL_ON_THESE_DAYS' => '在这些天里',
	'LBL_PRINT_REPORT' => '打印报表',
	'LBL_RECORDS' => '报表',
	'LBL_REPORT_CSV' => '导出CSV',
	'LBL_REPORT_DELETE_DENIED' => '您没有删除这个报表的权限',
	'LBL_REPORT_DETAILS' => '报表内容',
	'LBL_REPORT_EXPORT_EXCEL' => '导出为Excel',
	'LBL_REPORT_FOLDER' => '报表文件夹',
	'LBL_REPORT_NAME' => '报表名称',
	'LBL_REPORT_PRINT' => '打印',
	'LBL_REPORTS_LIST' => '报表列表',
	'LBL_REPORTS' => '报表列表',
	'LBL_RUN_REPORT' => '运行报告',
	'LBL_SAME_LEVEL_ROLES' => '同级角色',
	'LBL_SCHEDULE_REPORTS' => '定期生成报告',
	'LBL_SELECT_COLUMNS' => '选择列',
	'LBL_SELECTED_DATES' => '所选的日期',
	'LBL_SELECT_MONTH_AND_DAY' => '选择月份和日期',
	'LBL_SELECT_RECIEPIENTS' => '选择收件人',
	'LBL_SELECT_RELATED_MODULES' => '请选择相关模块', //Duplicated key-value pairs
	'LBL_SORT_ORDER' => '排序顺序',
	'LBL_SPECIFIC_DATE' => '在特定日期',
	'LBL_SPECIFIC_EMAIL_ADDRESS' => '发送到指定的电子邮件',
	'LBL_SUBORDINATE_ROLES' => '附属角色',
	'LBL_SUM' => '求和',
	'LBL_SUM_VALUE' => '总和',
	'LBL_TOP' => '顶部',
	'LBL_VIEW_DETAILS' => '查看细节',
	'LBL_WEEKLY' => '每周',
	'LBL_WRITE_YOUR_DESCRIPTION_HERE' => '请输入描述',
	'LBL_YEARLY' => '每年',
	'LBL_MAIN' => '主要',
	'LBL_SELECT_REPORT' => '选择报表',
	'LBL_FILE_TYPE' => '文件类型',
	'LBL_CSV' => 'CSV',
	'LBL_EXCEL' => 'EXCEL',
	//charts labels
	'LBL_SELECT_CHART_TYPE' => '选择图表类型',
	'LBL_CLICK_THROUGH_NOT_AVAILABLE' => '点击不可以选择多个模块',
	'LBL_TOTAL_SUM_OF' => '合计：%s',
	'LBL_AVG_OF' => '平均：%s',
	'LBL_MIN_OF' => '最小：%s',
	'LBL_MAX_OF' => '最大：%s',
	'LBL_RECORD_COUNT' => '记录数',
	'LBL_PIE_CHART' => '饼状图',
	'LBL_VERTICAL_BAR_CHART' => '垂直条形图',
	'LBL_HORIZONTAL_BAR_CHART' => '水平条形图',
	'LBL_LINE_CHART' => '折线图',
	'LBL_SELECT_CHART' => '选择图表',
	'LBL_CREATING_CHART_REPORT' => '创建图表报告',
	'LBL_EDITING_CHART_REPORT' => '编辑图表报表',
	'LBL_GENERATE_CHART' => '生成图表',
	'LBL_SELECT_GROUP_BY_FIELD' => '选择分组字段',
	'LBL_SELECT_DATA_FIELD' => '选择数据字段',
	'LBL_MODIFY_CONDITION' => '修改条件',
	'LBL_PLEASE_SELECT_ATLEAST_ONE_GROUP_FIELD_AND_DATA_FIELD' => '请选择至少一个分组字段和一个数据字段.',
	'LBL_FOR_BAR_GRAPH_AND_LINE_GRAPH_SELECT_3_MAX_DATA_FIELDS' => '对条形图和拆线图，您最多能选择3个数据字段.',
	'LBL_DETAIL_REPORT' => '详细报表',
	'LBL_CHARTS' => '图表',
	//Schedule Reports - Mail Content
	'LBL_AUTO_GENERATED_REPORT_EMAIL' => '这是自动生成的电子邮件，按照设置时间自动发送。',
	'LBL_PIVOT_REPORT' => '透视报表',
	'LBL_VIEW_CHARTDETAIL' => '图表预览',
];

$jsLanguageStrings = [
	'JS_CALCULATION_LINE_ITEM_FIELDS_SELECTION_LIMITATION' => '限制：这些字段（定价，折扣和数量）只能在其它计算字段没有选定时使用。',
	'JS_DUPLICATE_RECORD' => '复制报表',
	'JS_NO_CHART_DATA_AVAILABLE' => '数据不可用，请检查所选字段',
];

