<?php
/* ********************************************************************************
 *  Language     : 简体中文
 *  Version      : 3.4.87
 *  Author       : idercn.com | http://www.idercn.com
 *  Update Date  : 2016-10-17
  ********************************************************************************  
 * 此语言包版权如下所示：
 * 此文件内容受 vtigerCRM 的公共许可证1.0版保护，
 * 使用此文件表示您已默认遵守相关许可规定。
 * 您可以在遵守此许可证 "AS IS" 的基础上对软件进行分发。
 * 此语言包遵循 知识共享署名-非商业性使用-相同方式共享 2.5 中国大陆许可协议(Creative Commons) 2.5，
 * 大家可以免费下载使用，但请注明来源，并署名 · 非商业性使用 · 相同方式共享。
 * idercn无任何形式的担保，明示或暗示的保证。
 *+***********************************************************************************/
/* +***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * *********************************************************************************** */
$languageStrings = [
	'LBL_FIELD_MASK' => '字段掩码',
	'Calendar' => '待办事项',
	'Checkbox' => '复选框',
	'Currency' => '币种',
	'Date' => '日期',
	'Decimal' => '小数',
	'Email' => '电子邮件',
	'Integer' => '整数',
	'LayoutEditor' => '布局编辑器',
	'LBL_ACTIONS' => '操作',
	'LBL_ACTIVE' => '激活',
	'LBL_ADD_AFTER' => '添加在后面',
	'LBL_ADD_CUSTOM_BLOCK' => '添加自定义区块',
	'LBL_ADD_CUSTOM_FIELD' => '添加自定义字段',
	'LBL_ALWAYS_SHOW' => '总是显示',
	'LBL_ARRANGE_RELATED_LIST' => '排列相关列表',
	'LBL_ARRANGE_RELATED_TABS' => '模块-关联',
	'LBL_BLOCK_NAME' => '区块名称',
	'LBL_CLICK_HERE_TO_EDIT' => '点击这里编辑',
	'LBL_CREATE_CUSTOM_FIELD' => '创建自定义字段',
	'LBL_DECIMALS' => '小数',
	'LBL_DEFAULT_VALUE' => '默认值',
	'LBL_DELETE_CUSTOM_BLOCK' => '删除自定义区块',
	'LBL_DETAILVIEW_LAYOUT' => '详细视图布局',
	'LBL_DUPLICATE_FIELD_EXISTS' => '存在重复字段',
	'LBL_FIELD_NAME_IS_RESERVED' => '字段名称已保留',
	'LBL_DUPLICATES_EXIST' => '区块名称已存在',
	'LBL_INVALIDCHARACTER' => '输入非法字符',
	'LBL_ENTER_PICKLIST_VALUES' => '输入选择列表值...',
	'LBL_FIELDS_AND_LAYOUT_EDITOR' => '字段和布局编辑器',
	'LBL_INACTIVE_FIELDS' => '非活动字段', //Duplicated key-value pairs
	'LBL_LABEL_NAME' => '标签名',
	'LBL_LENGTH' => '长度',
	'LBL_MANDATORY_FIELD' => '必填字段',
	'LBL_MASS_EDIT' => '批量编辑',
	'LBL_NON_ROLE_BASED_PICKLIST' => '不是基于角色的选择列表',
	'LBL_NO_RELATED_INFORMATION' => '没有相关信息',
	'LBL_PICKLIST_VALUES' => '选择列表值',
	'LBL_QUICK_CREATE' => '快速创建',
	'LBL_REACTIVATE' => '重新启用',
	'LBL_ROLE_BASED_PICKLIST' => '基于角色的选择列表',
	'LBL_SAVE_FIELD_SEQUENCE' => '保存字段顺序',
	'LBL_SELECT_FIELD_TYPE' => '选择字段类型',
	'LBL_SELECT_MODULE' => '选择模块..',
	'LBL_SUMMARY_FIELD' => '摘要视图',
	'LBL_WRONG_FIELD_TYPE' => '错误的字段类型',
	'MultiSelectCombo' => '多选组合框',
	'Percent' => '百分数',
	'Phone' => '电话',
	'Picklist' => '选择列表',
	'Skype' => 'Skype',
	'TextArea' => '文本区域',
	'Text' => '文本',
	'Time' => '时间',
	'URL' => '网站',
	'LBL_REL_MODULE_LAYOUT_EDITOR' => '编辑相关的模块',
	'LBL_VISIBLE' => '可见',
	'LBL_HIDDEN' => '隐藏',
	//Yetiforce
	'LBL_RELATION_VALUES' => '选择模块',
	'LBL_FIELD_NAME' => '字段名称',
	'LBL_FIELD_TYPE' => '表',
	'Related1M' => '相关的叙述 1: m',
	'Editor' => '所见即所得编辑器',
	'LBL_DISPLAY_TYPE' => '公开程度',
	'LBL_DISPLAY_TYPE_1' => '现场到处可见',
	'LBL_DISPLAY_TYPE_2' => '可见只在预览中，不可编辑的字段',
	'LBL_DISPLAY_TYPE_3' => '仅在列表视图中可见的字段',
	'LBL_DISPLAY_TYPE_4' => '可见字段只能创建和预览，不能编辑',
	'LBL_DISPLAY_TYPE_10' => '现场可见无处不在不可编辑',
	'LBL_HELP_INFO' => '帮助图标',
	'LBL_GENERATED_TYPE' => '基本字段',
	'LBL_FIELD_TYPE0' => '基本(eg. vtiger_account)',
	'LBL_FIELD_TYPE1' => '额外的(eg. vtiger_accountcf)',
	'LBL_TREE_TEMPLATE' => '树',
	'Tree' => '领域的树',
	'LBL_FIELD_MASK_INFO' => '默认屏蔽定义<br>9 ︰ 数字<br>答 ︰ 按字母顺序<br>*: 字母数字<br><br>示例 ︰<br>（99) 9999-9999<br>48 999-999-999<br>aaa_999_aaa<br>dd/mm/yyyy',
	'MultiReferenceValue' => '相关模块中的值',
	'LBL_MULTI_REFERENCE_VALUE_MODULES' => '相关的模块',
	'LBL_MULTI_REFERENCE_VALUE_FIELDS' => '相关的领域',
	'LBL_MULTI_REFERENCE_VALUE_FILTER_FIELD' => '按字段筛选',
	'LBL_MULTI_REFERENCE_VALUE_FILTER_VALUE' => '按值筛选',
	'LBL_ADD_RELATION' => '添加关联',
	'LBL_REMOVE_RELATION' => '删除关联',
	'LBL_RELATION_TYPE' => '关系类型',
	'LBL_RELATION_ACTIONS' => '操作',
	'LBL_SOURCE_MODULE' => '源模块',
	'LBL_TARGET_MODULE' => '目标模块',
	'LBL_RELATION_LABLE' => '标签',
	'PLL_RELATED_LIST' => '多对多',
	'PLL_DEPENDENTS_LIST' => '一到多',
	'PLL_ATTACHMENTS' => '附件',
	'PLL_SPLITED_RELATED_LIST' => '多对多-与数据的分离',
	'PLL_ADD' => '添加',
	'PLL_SELECT' => '选择',
	// inventory tab
	'LBL_MANAGING_AN_ADVANCED_BLOCK' => '管理先进的块',
	'LBL_HEADLINE' => '标题',
	'LBL_BASIC_VERSE' => '基本地址',
	'LBL_ADDITIONAL_VERSE' => '附加地址',
	'LBL_ADVANCED_MODULE' => '高级检索',
	'LBL_BASIC_MODULE' => '基本',
	'LBL_EDITING_INVENTORY_FIELD' => '编辑',
	'LBL_CREATING_INVENTORY_FIELD' => '添加',
	'LBL_NAME_FIELD' => '名称',
	'LBL_COLSPAN' => '宽度[%]',
	'LBL_COMMENT' => '评论',
	'LBL_SELECT_TYPE_OF_INVENTORY' => '选择字段类型',
	'LBL_NEXT' => '下一个',
	'LBL_PARAMS_MODULES' => '模块',
	'LBL_PARAMS_LIMIT' => '限制',
	'LBL_DISPLAY_TYPE' => '字段类型',
	'LBL_DISPLAYTYPE_ALL' => '任何地方科技',
	'LBL_DISPLAYTYPE_READONLY' => '只读',
	'LBL_DISPLAYTYPE_ONLY_DETAIL' => '在详细视图可见',
	'LBL_DISPLAYTYPE_HIDDEN' => '隐藏',
	'LBL_FIELDS_EXISTS_IN_BLOCK' => '字段存在的块',
	'LBL_DELETE_CUSTOM_BLOCKS' => '不能删除非自定义块',
	'LBL_CURRENCY_DESC' => '列表中的可用货币，添加一种货币，基于当前汇率机制进行计算.',
	'LBL_DISCOUNT_MODE_DESC' => '可用折扣模式列表：团体或个人.',
	'LBL_TAX_MODE_DESC' => '可用税费模式列表：团体或个人.',
	'LBL_COMMENT_DESC' => '所见即所得的字段用于为给定元素输入到给定的元素，默认情况下该字段折叠。',
	'LBL_DISCOUNT_DESC' => '数值字段：用于输入选定元素的折扣，折扣可以从可用折扣列表中选择。 求和可以在系统管理中定义',
	'LBL_GROSS_PRICE_DESC' => '自动计算的非可编辑字段，包含一个元素的最终价格（折扣后和税后的价格）。',
	'LBL_ITEM_NAME_DESC' => '必填基本字段中，指定从中选择记录的模块。此外包括限制设置来阻止记录保存时达到的信贷限制。',
	'LBL_QUANTITY_DESC' => '数值字段用于输入每个记录的数量，例如产品数量，他的值必须大于0。',
	'LBL_UNIT_PRICE_DESC' => '用于输入指定记录单价的数值字段，例如一个产品的单价。',
	'LBL_TOTAL_PRICE_DESC' => '非可编辑字段自动计算，含有给定条件的净价折扣（数量*单价）。',
	'LBL_DISCOUNT_PRICE_DESC' => '非可编辑字段自动计算，折扣包括折后净价折扣（净价格-折扣）。',
	'LBL_TAX_DESC' => '数值字段用于输入给定元素的税值，税种可以从可用税种列表中选择。 求和可以在系统管理中定义。',
	'LBL_VALUE_DESC' => '用户可以输入任何值的附加字段。',
	'LBL_REFERENCE_DESC' => '用于关联系统中任何记录给定元素的附件字段。',
	'LBL_PURCHASE_DESC' => '用于输入指定元素的购买/采集值的数值字段。',
	'LBL_MARGIN_DESC' => '非可编辑字段自动计算，包含给定元素的利润值 （价格折扣后-"购买），不包括税。',
	'LBL_MARGIN_PERCENT_DESC' => '自动计算的非可编辑字段，包含用百分比表示的利润值。',
	'LBL_ITEM_NUMBER' => '项目编号',
	'LBL_ITEM_NUMBER_DESC' => '包括项目编号的字段',
	'LBL_PICKLIST_FIELD' => '从字段中选择',
	'LBL_PICKLIST_FIELD_DESC' => '从选定的模块中的任何字段的值中选择值列表',
	'LBL_DEACTIVATE_FAVORITES' => '停用添加到收藏夹功能',
	'LBL_ACTIVATE_FAVORITES' => '激活添加到收藏夹功能',
	'LBL_HEADER_FIELD' => '在阅览窗口头部可见',
	'LBL_COPY' => '复制',
	'LBL_STANDARD_FIELDS' => '标准字段',
	'LBL_ADVANCED_BLOCK_FIELDS' => '高级区块字段',
	'LBL_ADD_ADVANCED_BLOCK_FIELDS' => '添加高级区块字段',
	'LBL_MAX_LENGTH_TEXT' => '最大文字长度',
	'LBL_MAX_WIDTH_COLUMN' => '列宽[%]'
];

$jsLanguageStrings = [
	'JS_BLOCK_NAME_EXISTS' => '区块名称已存在',
	'JS_BLOCK_SEQUENCE_UPDATED' => '区块顺序已经更新',
	'JS_BLOCK_VISIBILITY_HIDE' => '此区块已设置为隐藏',
	'JS_BLOCK_VISIBILITY_SHOW' => '此区块已设置为显示',
	'JS_CUSTOM_BLOCK_ADDED' => '新的自定义区块已添加',
	'JS_CUSTOM_BLOCK_DELETED' => '自定义区块已删除',
	'JS_CUSTOM_FIELD_ADDED' => '新的自定义字段已添加',
	'JS_CUSTOM_FIELD_DELETED' => '自定义字段已删除',
	'JS_DUPLICATES_VALUES_FOUND' => '发现重复值',
	'JS_FIELD_DETAILS_SAVED' => '字段信息已保存',
	'JS_FIELD_SEQUENCE_UPDATED' => '字段顺序已更新',
	'JS_LENGTH_SHOULD_BE_LESS_THAN_EQUAL_TO' => '长度应该小于或等于',
	'JS_NO_HIDDEN_FIELDS_EXISTS' => '没有禁用的字段',
	'JS_NOT_ALLOWED' => '不能使用',
	'JS_PLEASE_ENTER_NUMBER_IN_RANGE_2TO5' => '小数的取值范围为2 5',
	'JS_RELATED_INFO_SAVED' => '相关信息已保存',
	'JS_SAVE_THE_CHANGES_TO_UPDATE_FIELD_SEQUENCE' => '字段顺序已更新',
	'JS_SELECTED_FIELDS_REACTIVATED' => '所选定的字段已重新激活',
	'JS_SPECIAL_CHARACTERS' => '特殊字符如',
	'JS_SAVED_CHANGE_STATUS_1' => '已启用相关的模块',
	'JS_SAVED_CHANGE_STATUS_0' => '相关的模块已被禁用',
	'JS_UPDATE_SEQUENCE' => '已保存的相关模块的新序列',
	'JS_UPDATED_FIELD_LIST_MODULE_RELATED' => '字段列表已更新',
	'JS_FIELD_CAN_NOT_BE_EMPTY' => '字段不能为空',
	'JS_RESERVED_PICKLIST_NAME' => '此选择列表名称是保留字.',
	'JS_REMOVE_RELATION_OK' => '已成功删除关联。',
	'JS_DELETE_RELATION_CONFIRMATION' => '您确定您要删除吗？',
	'JS_DELETE_INVENTORY_CONFIRMATION' => '你确定你想要删除的元素从块？',
	'JS_EXTENDED_MODULE' => '你确定你想要更改的模块类型？?',
	'JS_SAVE_CHANGES' => '更改已成功保存。',
	'JS_NOTIFY_COPY_TEXT' => '已复制到剪贴板',
	'JS_NOTIFY_COPY_TITLE' => '文本',
];
